name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd backend && mvn -B package --file pom.xml
    - name: Run backend tests
      run: cd backend && mvn test
    - name: OWASP dependency check
      run: cd backend && mvn org.owasp:dependency-check-maven:check
    
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install dependencies
      run: cd frontend && npm ci
    - name: Run linting
      run: cd frontend && npm run lint
    - name: Run frontend tests
      run: cd frontend && npm run test:ci
    - name: Build Angular app
      run: cd frontend && npm run build --prod
      
  security-scan:
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]
    steps:
    - uses: actions/checkout@v3
    - name: Run SAST scan
      uses: github/codeql-action/init@v2
      with:
        languages: javascript, java
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
